[package]
name = "lean-lsp"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
bytes = "1.10.1"
clap = { version = "4.5.46", features = ["derive", "env"] }
console-subscriber = "0.4.1"
derive_more = { version = "2.0.1", features = ["constructor"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
tokio = { version = "1.47.1", features = ["macros", "process", "rt-multi-thread"] }
tracing = { version = "0.1.41", features = ["valuable"] }
tracing-subscriber = { version = "0.3.20", features = ["json", "valuable"] }
ulid = "1.2.1"
valuable = "0.1.1"

[lints.clippy]
pedantic = { level = "deny", priority = -1 }
unit_arg = "allow"
