[package]
name = "lean-lsp"
version = "0.1.0"
edition.workspace = true

[dependencies]
clap = { version = "4.5.46", features = ["derive", "env"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
tokio = "1.47.1"
